# Generated by Django 4.1.13 on 2024-04-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_alter_doctor_information_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_information',
            name='register_status',
            field=models.CharField(blank=True, default='Pending', max_length=200, null=True),
        ),
    ]
